### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by ButGuc** [alessioforte/transee#10]
![image](https://user-images.githubusercontent.com/5721796/47610331-4cca3700-da5b-11e8-9143-4d4dcd3f7c05.png)

**Comment by UNiXMIT** [comment]
I just updated and now I get this error always. It's unusable now.

**Comment by proactivematter** [comment]
I'm getting this too, regardless of input.

**Comment by alessioforte** [comment]
Sorry guys, I don't know why this happen... I have had this problem and if I use a vpn or restart my modem the app seems to works. It's possible that google reject your requests?

**Comment by UNiXMIT** [comment]
It happens regardless of which network I am on. Tried uninstalling and installing other versions but it’s always the same issue.

**Comment by ButGuc** [comment]
no problem on the user side looks like,  maybe has problem on token ?

**Comment by ButGuc** [comment]
c3fa55fa6bdfbd891149076cc29af888cfcc1464 solved the problem this change.

right now we need a release

![ek aciklama](https://user-images.githubusercontent.com/5721796/47957757-37aa5680-dfcd-11e8-9dff-0bfeac40f197.png)

**Comment by alessioforte** [comment]
There was ah issue with the token, anyway google rejects too many requests.
I tried to reduce the number of requests on typing.
I've released 1.2.4 version, you can test and leave me your feedback
Thanks!

**Comment by ButGuc** [comment]
problem is solved.

@alessioforte @UNiXMIT @proactivematter  thanks.
